const String d = 'assets/img/';
const Map<String, String> assetsUrl = {
  'cafe': '${d}cafe.png',
  'calendar': '${d}calendar.png',
  'cancel2': '${d}cancel2.png',
  'checked': '${d}checked.png',
  'closeRSvg': '${d}closeRoundIcon.svg',
  'heart': '${d}heart.png',
  'hotel': '${d}hotel.png',
  'info': '${d}info.png',
  'museum': '${d}museum.png',
  'park': '${d}park.png',
  'restaurant': '${d}restaurant.png',
  'searchSSvg': '${d}searchIconSettings.svg',
  'searchS': '${d}searchSettings.png',
  'share': '${d}share.png',
  'special': '${d}special.png',
  'trashS': '${d}trashIcon.svg',
  'union': '${d}union.png',
};
