const Map<String, String> words = {
  'cancel': 'Отмена',
  'newPlace': 'Новое место',
  'category': 'Категория',
  'categories': 'Категории',
  'noChoose': 'Не выбрано',
  'namePlace': 'Название',
  'latitude': 'Широта',
  'longitude': 'Долгота',
  'pointOnMap': 'Указать на карте',
  'description': 'Описание',
  'clear': 'Очистить',
  'Hotel': 'Отель',
  'Restaurant': 'Ресторан',
  'specialPlace': 'Особое место',
  'Park': 'Парк',
  'Museum': 'Музей',
  'Cafe': 'Кафе',
  'Distance': 'Расстояние',
  'from': 'от',
  'to': 'до',
  'km': 'км',
  'showD': 'Показать',
  'Settings': 'Настройки',
  'darkThemes': 'Тёмная тема',
  'lightThemes': 'Светлая тема',
  'watchTutorial': 'Смотреть туториал',
  'Empty': 'Пусто',
  'completeTheRoute': 'Завершите маршрут\n чтобы место попало сюда.',
  'goalIsAchieved': 'Цель достигнута',
  'MarkPlacesYouLike': 'Отмечайте понравившиеся\n места и они появятся здесь.',
  'ScheduledFor': 'Запланировано на ',
  'BuildARoute': 'Постройте маршрут',
  'ToSchedule': 'Запланировать',
  'ToFavorites': 'В Избранное',
  'NewPlace': 'Новое место',
  'List': 'Список',
  'interestingPlaces': 'интересных мест',
  'Search': 'Поиск',
  'NothingFound': 'Ничего не найдено',
  'TryToChangeTheParameters': 'Попробуйте изменить параметы \nпоиска',
  'YouWereLookingFor': 'Вы искали',
  'ClearHistory': 'Очистить историю',
  'Favorites': 'Избранное',
  'WantToVisit': 'Хочу посетить',
  'Visited': 'Посетил',
  'Skip': 'Пропустить',
  'WelcomeToGuide': 'Добро пожаловать\nв путеводитель',
  'FindNewLocationAndSave': 'Ищи новые локации и сохраняй\nсамые любимые',
  'BuildARouteAndGo': 'Построй маршрут\nи отправляйся в путь',
  'ReachYourGoalAsPossibleFastAnd':
      'Достигай цели максимально\nбыстро и комфортно.',
  'AddPlacesWhichIFoundMyself': 'Добавляй места,\nкоторые нашёл сам',
  'ShareTheMostInterestingAndHelpUsBecomeBetter':
      'Делись самыми интересными\nи помоги нам стать лучше!',
  'onYourMarks': 'на старт',
  'Camera': 'Камера',
  'Photo': 'Фотография',
  'File': 'Файл',
  'confirm': 'Подтвердить',
  'chooseDate': 'Выберите дату',
};

// words['confirm']!
