name: places
description: A new Flutter places project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  fonts:
  - family: Roboto     
    fonts:
      - asset: res/fonts/Roboto-Regular.ttf

  uses-material-design: true
  
  assets:
    - res/
  

